#+title: README
#+autor: anthe

Hi! Here is my desktop environment files. I use emacs with evil mode enabled (vim emulator), as well as exwm (emacs X window manager). I am happy to share my config as well as getting feedback. I am relatively new to emacs (Jan 2025, burying vscode in 2024), my config is still very messy but I am learning and updating it regularly.

* About me
I am a PhD student in Physics, focusing on glaciology. I do numerical modelling. I am enthusiastic about machine learning methods and trying to use them in my project.
* Why I use emacs
- Evil mode: basically vim everywhere = goat power ('I use vim btw').
- IDE:
  - Main languages: Python, C++, bash, Elips
  - LSP and DAP
  - Version control (magit)
- Terminal emulation (multi-vterm).
- Org mode: note taking, knowledge network (roam), todos, agenda, latex rendering, presentations, programming, accountability...
- Email client (mu4e).
- IRC
- Scientific research:
  - Writing: Org and Latex
  - Bibliography manager + integration of roam
- LLM assistant client (gptel, my favorite LLM is Mistral/Codestral)
- Window manager (exwm): managing my none-emacs buffers (Firefox, discord, Spotify, ncview, matplotlib, Ardour...).

** System:
- Laptop: Dell inspiron 14 5420
- CPU: 12th Gen Intel i7-1255U (12) @ 4.700GHz
- RAM: SODIMM 2x16G
- OS: Ubuntu 24.10 (but planning to go to arch or fedora soon)

* Workflow as a PhD student
I am planing to document a bit more here my workflow in Emacs as a scholar. Make research efficient and fun!
